# Generated by Django 5.2.5 on 2025-08-19 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Patient full name', max_length=100)),
                ('email', models.EmailField(help_text='Patient email address', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Patient phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(help_text='Patient date of birth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment')),
                ('reason', models.TextField(help_text='Reason for the appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'unique_together': {('patient', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
